version: '3.8'

volumes:
  db_data:

networks:
  geniusee:
    name: geniusee-network

services:

  nginx:
    image: nginx:1.19.3-alpine
    container_name: nginx
    volumes:
      - ./src:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php
    networks:
      - geniusee

  php:
    image: vagifrzada/phpdock:latest
    container_name: php
    volumes:
      - ./src:/app
    environment:
      - XDG_CONFIG_HOME=/app/storage/framework
    depends_on:
      - db
    networks:
      - geniusee

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - 3308:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: geniusee
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: geniusee
      MYSQL_DATABASE: geniusee
      SERVICE_NAME: mysql
      TZ: Europe/Kiev
    command: --sql_mode="" --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - geniusee